### ISSUE TITLE
Weird crash with latest version.

### ISSUE THREAD

**Issue by xJon** [hilburn/NotEnoughResources#29]
http://pastebin.com/K2thkeq0
Thank you.

**Comment by hilburn** [comment]
@way2muchnoise - your thing broke again!
We'll look into it - trying to get a new release ready over the next week or so

**Comment by The-1-7-10-Pack** [comment]
Awesome, thanks :)

**Comment by xJon** [comment]
I guess I can close this one if you applied a fix for it.
Can't wait for the next stable release.
