### ISSUE TITLE
Everything shows up as enchantable in your "Enchantments" NEI handler

### ISSUE THREAD

**Issue by BBoldt** [hilburn/NotEnoughResources#32]
Using latest version at the time of this posting.

NotEnoughResources-1.7.10-0.1.0.86

![](http://i.imgur.com/cQr772c.png)
![](http://i.imgur.com/Pbo4T3R.png)
![](http://i.imgur.com/8pyZzAF.png)

It usually shows up as either "Soulbound" or "Flim Flam"

**Comment by way2muchnoise** [comment]
@BBoldt Well that means everything can be souldbound or flimflammed

**Comment by BBoldt** [comment]
@way2muchnoise 

Actually, you're right. 
It just seemed weird to me, and a bit annoying seeing it for every single thing in the game.

**Comment by way2muchnoise** [comment]
@BBoldt I'll see if I can add something to disable certain enchantments
