### ISSUE TITLE
Can't enter a world with the new stable version of Forestry & NER

### ISSUE THREAD

**Issue by xJon** [hilburn/NotEnoughResources#34]
It just kicks me out when I try to enter. Forestry version 3.4.0.7: http://jenkins.ic2.player.to/job/Forestry/7/
Log: http://pastebin.com/1nqt8JfE
Thanks.

**Comment by hilburn** [comment]
Can you make sure you're using the latest NER - as this was an issue in a quite old version.
Jenkins downloads can be found [here](http://jenkins.jakimfett.com/job/NotEnoughResources/)

**Comment by The-1-7-10-Pack** [comment]
Indeed I used build #55 for this one. I can't launch with build #91 though: http://pastebin.com/LB7CPZMM

**Comment by xJon** [comment]
Indeed I were using build #55 in this report.
I am not able to launch with the latest build though (#91): http://pastebin.com/LB7CPZMM
