### ISSUE TITLE
Server can't start with Cauldron

### ISSUE THREAD

**Issue by devryb** [hilburn/NotEnoughResources#35]
Apologies if this is a duplicate this is with build 86
When using Cauldron the server won't start

http://pastebin.com/Ax7D09TQ

**Comment by hilburn** [comment]
I will look into this but generally speaking Cauldron is something of a dead project, no longer being developed or particularly compatible with newer versions of Forge and Forge Mods.

Hopefully I'll be able to find a fix, but just to warn you, it might not be possible

**Comment by devryb** [comment]
Thanks for taking the time to look!

**Comment by bloodmc** [comment]
@hilburn 

https://github.com/hilburn/NotEnoughResources/blob/master/src/main/java/neresources/compatibility/minecraft/MinecraftCompat.java#L106

Why are you passing null world objects when registering entities? that just seems hacky... If you really need to do this, just pass the default world 
```java
DimensionManager.getWorld(0)
```

**Comment by hilburn** [comment]
Pretty sure that was returning null objects in that stage of loading anyway when I checked it, but I'll double check

**Comment by hilburn** [comment]
![](http://puu.sh/fMBZ9/c6547a699c.png)

**Comment by bloodmc** [comment]
@hilburn Is there an issue with registering during the FMLServerStartingEvent ? This will have the world instance.

**Comment by hilburn** [comment]
Pretty sure there was, but I can't remember what exactly.. I'll check my notes

**Comment by hilburn** [comment]
@bloodmc - it appears @way2muchnoise  solved the particular issue that was causing the problem with FMLServer-X-Event accidentally while working on something else. So made those changes
