### ISSUE TITLE
Freezes Game Caused by usage of texturepack

### ISSUE THREAD

**Issue by AntonyBearpark** [hilburn/NotEnoughResources#37]
I'm not sure what is causing it to freeze and crash but when I appear on the inventory and choose an item, I click the arrow buttons to see how to create the item, then as soon as I get to the Mob Drops of Dungeon Chests page, the game slows to a halt. I can hover over buttons and the hover states take a few seconds to change, but clicking buttons and shortcut keys does nothing. I have to close and restart the game.

If you need anything from my game to find where the error is being created, let me know and I'll attempt to get that information for you. No one else on our server is having the problem.

**Comment by way2muchnoise** [comment]
@AntonyBearpar Does this happen with only NER and NEI installed? What version are you using? Make sure to get the [latest dev build](http://jenkins.jakimfett.com/job/NotEnoughResources/) first

**Comment by AntonyBearpark** [comment]
We are using Feed the Beast Infinity 1.7 1.0.0

**Comment by way2muchnoise** [comment]
@AntonyBearpark Manually update NER to the latest dev build and see if that fixes it

**Comment by AntonyBearpark** [comment]
Within the server or just myself? How is that done?

**Comment by way2muchnoise** [comment]
You download the latest version and replace it in the mods folder. If you want to connect to a server you'll have to update it there to

**Comment by AntonyBearpark** [comment]
Ok will have to check if this works in a few days when I can get the host to update the server

**Comment by way2muchnoise** [comment]
@AntonyBearpark You can test it in a solo world but I just downloaded FTB Infinity 1.0.1 (which recommended) and I can access both the chest and mob drop screens. What are your system specs and minecraft arguments(java version / ram allocated to mc)?

**Comment by AntonyBearpark** [comment]
Had a test with a few things, and turned out that it is the Texture Pack I
was using that was crashing it. I was using John Smith Legacy and it showed
a slightly different panel to what I can see now. I'm guessing testing
hasn't been done in any texture packs, though if there is any packs that
have been tested as fine, I'd prefer them to the default to Minecraft?


*Antony Bearpark*
antonybearpark.co.uk
blog.antonybearpark.co.uk

**Comment by way2muchnoise** [comment]
@AntonyBearpark I don't really play with texture pack but I will look into the issue
