### ISSUE TITLE
NEI Ore Gen Integration freezes computer entirely

### ISSUE THREAD

**Issue by pizzapants184** [hilburn/NotEnoughResources#38]
OS: Lubuntu 14.04.01 LTS
Java: Oracle Java 7u71
Crash Report: None (computer completely frozen)
For usually less than a second after pulling up the ore gen recipie, it works, then the entire computer freezes except the mouse, which freezes a few seconds later.
I don't know if this is my OS, the Java version, or the mod, but it definitely only happens when NEI shows the ore gen rates for an ore. This does not affect any other Not Enough Resources info pages in NEI, only the ore gen.
EDIT: 
Modpack: Infinity 1.0.1
Mod Version: 1.0.86
Currently testing with 1.0.95
EDIT2: Still happens with latest dev build (95)

**Comment by Sasikaa** [comment]
Oh yes... This is my problem...How CAN fix this??? Java 8 installing?

**Comment by Sasikaa** [comment]
OMG! This problem is the TEXTURE pack... The JSTR texture pack and this mod is not love each other...

**Comment by hilburn** [comment]
JSTR? that's really strange and I will look into it

**Comment by pizzapants184** [comment]
I wasn't using a texturepack, just the vanilla textures. Should I try with a texturepack?
