### ISSUE TITLE
Must load SSP, *then* SMP for NER to show in NEI

### ISSUE THREAD

**Issue by warezit** [hilburn/NotEnoughResources#42]
So, I have added NER into my custom modpack, and the pack loads fine (generates a config for NER), but I have been paging through all the "recipes" and "uses" pages in NEI for all the ores & mob drops, and I don't see any pages with graphs. I have also checked all the keybinds, and I don't see any options there for NER.

Am I missing something? (I feel retarded...) How do I get to see the graphs/use this mod?

**Comment by way2muchnoise** [comment]
@warezit Recipe for ores should give the graphs and does recipes for eg. rotten flesh will give you the mod view

**Comment by EnigmaRM** [comment]
Having the same problem here.  FTB Infinity pack and I am not seeing any ore gen graphs or mob drops in my client, nor do any of the people playing on my server.  Is there a setting that we need to turn on or some such thing?

**Comment by EnigmaRM** [comment]
I'm having this same issue when connecting to my server with NER installed.  It works perfectly on the same client when in a SSP world, but when I connect to my server, I get nothing from NER.

**Comment by warezit** [comment]
@EnigmaRM I appreciate you investigating and sharing your notes...

I have done the same as you, and I can confirm I get the same results.

Diving straight into multiplayer, NER doesn't show up in the Ore Recipe NEI screens.

If I load a Single Player World first, save & quit, THEN goto my Multiplayer Server, NER shows up fine in NEI...

Odd..

**Comment by warezit** [comment]
Side note, just for clarity, here are the versions I am using:
NotEnoughResources-1.7.10-0.1.0.96
NotEnoughItems-1.7.10-1.0.4.90-universal
Forge 1.7.10-10.13.2.1291

**Comment by way2muchnoise** [comment]
Ah the diving straight into MP really helps me out here. I'll see what I can.
