### ISSUE TITLE
Compatibility NPE with FML? Not sure

### ISSUE THREAD

**Issue by cocopuffs99** [hilburn/NotEnoughResources#43]
Hey Guys,

I've been getting this error that sometimes causes the server to stop and if I try to reload into a world from the main menu it just resets the screen back to the main menu and doesn't let me load a world.  Any ideas?  Thanks for taking a look.

Here is the ATLauncher log:  http://paste.atlauncher.com/view/c0074478
The FML log is too large to post here but I can upload it to a link if needed; here is a bit of it I can fit here: http://pastebin.com/FrsgBGXd

**Comment by way2muchnoise** [comment]
@cocopuffs99 Please use pastebin or alike to post logs like this don't just dump it in an issue

**Comment by cocopuffs99** [comment]
trying to ! sorry. i was trying to use the spoiler markdown but I couldnt get it to work.  I'll edit it out

**Comment by way2muchnoise** [comment]
@cocopuffs99 What is the version of forge used?

**Comment by cocopuffs99** [comment]
forge #1370

**Comment by way2muchnoise** [comment]
Hmmm guess I'll update the forge version we build against and see

**Comment by cocopuffs99** [comment]
New crash again in a different modpack- thought maybe it was compatibility with ProjectE but they said to let neresources know:  https://github.com/sinkillerj/ProjectE/issues/680#issuecomment-97313282

NPE causing fatal server shutdown, full log: http://paste.atlauncher.com/view/043b337c

**Comment by way2muchnoise** [comment]
@cocopuffs99 The log you posted seems to be a version issue with mobproperties will look into it

**Comment by way2muchnoise** [comment]
@cocopuffs99 Updating mobproperties to 0.3.5 should fix it since that is what we build against.

**Comment by cocopuffs99** [comment]
@way2muchnoise Thanks! I had no idea they had a specific fix for comp with neresources api from 0.3.4 to 0.3.5 and that my version was outdated.  *diamond*  ;)

**Comment by cocopuffs99** [comment]
@way2muchnoise do you think this is the same error as the first post I made for this issue (with the other modpack aka RR3)?  should I close it/mark as fixed?

thanks

**Comment by way2muchnoise** [comment]
@cocopuffs99 I have no idea what the first one is about it crashes during a call to some reflection stuff and basically gives no indication of what it is. So I say open a new on if it happens again and I'll close this issue
