### ISSUE TITLE
More localization

### ISSUE THREAD

**Issue by Adaptivity** [hilburn/NotEnoughResources#44]
1) "Any" in hardcoded in Biomes and in Light level. 
2) "Light level" hardcoded itself. 
3) *ner.stacks* string should have %s for swapping with number.
4) "Any" displays on NEI item panel -> http://i.imgur.com/cBuZif1.jpg

**Comment by way2muchnoise** [comment]
@Adaptivity I did things you can go ahead and do some more ru_RU sweetness

**Comment by Adaptivity** [comment]
Thank you. ru_RU.lang is done, just need todo some testing. Also, you fixed issue number 4?

**Comment by way2muchnoise** [comment]
Yes I did in 2c7ebe9c21733a0fc911b2d393013036fa228759
