### ISSUE TITLE
NEI enchantment view ('I') drops my fps to around 0.1 (yes, 1 frame per 10 seconds!!!)

### ISSUE THREAD

**Issue by shadoxxhd** [hilburn/NotEnoughResources#49]
happens only with this mod installed. infinity 1.5.1. v0.1.0.95. removing it causes mod rejection (playing on standard infinity 1.5.1 server). tried it without this mod in SP, framerate is fine (60fps vsync). with this mod SP, fps killed. solution?

**Comment by hilburn** [comment]
Should be fixed in latest versions, but please reopen if 0.1.0.106+ cause issues
