### ISSUE TITLE
API is not a api

### ISSUE THREAD

**Issue by Speiger** [hilburn/NotEnoughResources#56]
Just got started on the NER support for IC2 classic loading all API files in then...
What happens... Right the API requires ModClasses. Even really Deep core classes...
That you should fix...

**Comment by way2muchnoise** [comment]
What? Could you point out where it requires ModClasses?

**Comment by Speiger** [comment]
https://github.com/hilburn/NotEnoughResources/blob/master/src/main/java/neresources/api/messages/SendMessage.java#L7
And line 6

so it requires the Message registry and the config class which requires the settings class which requires a lot more other classes which mean you require the whole mod... and a couple submods

**Comment by way2muchnoise** [comment]
ah those shouldn't be in the API my bad, that is/was some WIP stuff

**Comment by Speiger** [comment]
Simply the API should be build and stored in his own seperate area. And the Mod is reading out of it. Else it would not work. (Talking from experience)

**Comment by way2muchnoise** [comment]
I know what an API is and how it is supposed to work. I was working on things and never continued with it so it was some WIP stuff that wasn't cleaned properly

**Comment by Speiger** [comment]
I do not blame you or something just wanted to help^^ Anyway thanks for fixing.
