### ISSUE TITLE
World unable to load with NER

### ISSUE THREAD

**Issue by Pyeroh** [hilburn/NotEnoughResources#57]
When I have NER enabled, I can't load any world. The game is not crashing, it's just unable to load any world.
Here's the "crashlog" (even if it doesn't really crash) : http://pastebin.com/MMBGasPs
For information, here's the MobProperties that may cause the crash : http://pastebin.com/DLFiBckz

It's in french (so am I), so a bit of explanation : this script is meant to make the Enderdragon respawn when an enderman is killed on top of a dragon egg in the End.

EDIT : in the wiki, "if_on_block_X" should be used with an integer, but with the string ID it works too. As  int ID should be deprecated, maybe a block should be found by its string ID insted of int ID...

**Comment by hilburn** [comment]
I'll change it to support both when I get a chance - the string support is new since I wrote that compatibility. Until then, the int format should work for now.

**Comment by Pyeroh** [comment]
Indeed, the int format works. I changed my script to use the int ID (122) instead of "dragon_egg", and it works.
Let this issue be a simple reminder of a "todo", as it's not blocking =)
