### ISSUE TITLE
Not working correctly with ATG

### ISSUE THREAD

**Issue by topher2010** [hilburn/NotEnoughResources#58]
When using NotEnoughResources with ATG latest version, it isn't showing the correct y-levels for ores.  Is this an issue with mod interactions?  If so, I can provide my mod list if it would help.

**Comment by hilburn** [comment]
Does ATG fuck with ore levels? If you create a new world without the ATG world type does it then work

**Comment by topher2010** [comment]
My apologies for taking so long to get back to you.  Work has been hectic.  I'm testing this now and will update once i test without ATG.
