### ISSUE TITLE
[Request] Reliquary mob drop support

### ISSUE THREAD

**Issue by BBoldt** [hilburn/NotEnoughResources#59]
Like 90% of the stuff in Xeno's Reliquary requires items which drop from mobs, I feel like a lot of people get turned off from the mod because they don't know what mob drops what item.

http://minecraft.curseforge.com/projects/reliquary

**Comment by hilburn** [comment]
I'll look into it when I get a chance

**Comment by hilburn** [comment]
Probably be this weekend at the earliest

**Comment by FantasyTeddy** [comment]
Sorry @hilburn, I began working on this before you replied... I hope you don't mind that I took a shot at it.

**Comment by way2muchnoise** [comment]
@FantasyTeddy I'll give it try

**Comment by way2muchnoise** [comment]
@FantasyTeddy I cleaned up some things so you have we have no try catch. Would have loved to use the versioning but for some reason they don't have a good one.

**Comment by FantasyTeddy** [comment]
@way2muchnoise Great, thanks for the merge!
