### ISSUE TITLE
Not showing any modded mobs

### ISSUE THREAD

**Issue by fishmealx** [hilburn/NotEnoughResources#62]
NEI 1.0.5.111. Modded ores are showing up, almost no modded mobs.

I have many mods, but the only one whose drops I can find is Thaumcraft.

Mods:
ID,Name,Version,Custom Container,Disableable,Dependencies
mcp,Minecraft Coder Pack,9.05,true,YES,[]
FML,Forge Mod Loader,7.10.99.99,true,NEVER,[]
Forge,Minecraft Forge,10.13.4.1448,true,NEVER,[]
appliedenergistics2-core,AppliedEnergistics2 Core,rv2-stable-10,true,NEVER,[]
Aroma1997Core,Aroma1997Core,1.0.2.16,true,NEVER,[]
CodeChickenCore,CodeChicken Core,1.0.7.47,true,NEVER,[]
ivtoolkit,1.2,IvToolkit,true,NEVER,[]
MCVanillaTweaks,Mariculture - Vanilla Tweaks,1.0,true,NEVER,[]
Micdoodlecore,Micdoodle8 Core,,true,NEVER,"[required-after:Forge@[10.12.2.1148,)]"
NotEnoughItems,Not Enough Items,1.0.5.111,true,NEVER,"[CodeChickenCore@[1.0.7,)]"
OpenComputers|Core,OpenComputers (Core),1.5.18.36,true,NEVER,[]
OpenEye,OpenEye,0.6,true,NEVER,[]
PotionExtensionCore,PotionExtensionCore,1.7.10-1.1.0,true,NEVER,[]
ThaumicTinkerer-preloader,Thaumic Tinkerer Core,0.1,true,NEVER,[]
OpenModsCore,OpenModsCore,0.8,true,NEVER,[]
<CoFH ASM>,CoFH ASM,000,true,NEVER,[]
debug,debug,1.0,false,RESTART,[]
battlegear2,Mine & Blade Battlegear 2 - Bullseye,1.7.10,false,RESTART,[]
bspkrsCore,bspkrsCore,6.16,false,DEPENDENCIES,"[Forge@[10.13.2.1291,)]"
ArmorStatusHUD,ArmorStatusHUD,1.28,false,RESTART,"[bspkrsCore@[6.15,)]"
DamageIndicatorsMod,Damage Indicators,3.2.3,false,RESTART,[]
StartingInventory,StartingInventory,1.7.10.r03,false,RESTART,"[bspkrsCore@[6.15,)]"
StatusEffectHUD,StatusEffectHUD,1.27,false,RESTART,"[bspkrsCore@[6.15,)]"
Treecapitator,Treecapitator,1.7.10,false,RESTART,"[Forge@[10.13.2.1232,), bspkrsCore@[6.15,)]"
appliedenergistics2,Applied Energistics 2,rv2-stable-10,false,DEPENDENCIES,"[appliedenergistics2-core, Forge@[10.13.2.1291,)]"
bdlib,BD Lib,1.9.3.107,false,DEPENDENCIES,[]
ae2stuff,AE2 Stuff,0.4.3.47,false,RESTART,"[appliedenergistics2, bdlib@[1.9.1.97,)]"
AnimationAPI,AnimationAPI,1.2.4,false,RESTART,[]
AppleCore,AppleCore,1.1.0,false,DEPENDENCIES,[]
ArchimedesShips,Archimedes' Ships,1.7.10 v1.7.1,false,RESTART,[]
Aroma1997CoreHelper,Aroma1997Core|Helper,1.0.2.16,false,RESTART,[]
Aroma1997sDimension,Aroma1997's Dimensional World,1.0,false,RESTART,[Aroma1997Core]
AromaBackup,AromaBackup,0.0.0.5,false,RESTART,[Aroma1997Core]
Baubles,Baubles,1.0.1.10,false,DEPENDENCIES,"[Forge@[10.13.2,)]"
Artifacts,Artifacts,1.1.3,false,RESTART,[]
asielib,asielib,0.3.4,false,DEPENDENCIES,[]
aura,Aura Cascade,unspecified,false,RESTART,[Baubles]
thebombzenapi,ThebombzenAPI,2.4.2,false,DEPENDENCIES,[]
autoswitch,AutoSwitch,5.1.1,false,RESTART,[thebombzenapi]
BetterChests,BetterChests,1.1.1.9,false,RESTART,[Aroma1997Core]
betterrecords,Better Records,1.7.10-1.1.9,false,RESTART,[]
BiblioCraft,BiblioCraft,1.11.2,false,RESTART,[]
BiomesOPlenty,Biomes O' Plenty,2.1.0,false,RESTART,"[Natura, Forge@[10.12.2.1147,)]"
BiblioWoodsBoP,BiblioWoods Biomes O'Plenty Edition,1.9,false,RESTART,"[BiblioCraft, BiomesOPlenty]"
HardcoreEnderExpansion,Hardcore Ender Expansion,1.8.4,false,RESTART,[]
CoFHCore,CoFH Core,1.7.10R3.0.4B1,false,DEPENDENCIES,"[Forge@[10.13.3.1448,10.14)]"
BuildCraft|Core,BuildCraft,7.1.9,false,DEPENDENCIES,"[Forge@[10.13.2.1236,)]"
Forestry,Forestry for Minecraft,3.6.11.2,false,DEPENDENCIES,"[Forge@[10.13.0.1207,), Buildcraft|Core@[6.1.7,), ExtrabiomesXL, BiomesOPlenty, IC2@[2.0.140,), Natura@[2.2.0,), HardcoreEnderExpansion]"
BiblioWoodsForestry,BiblioWoods Forestry Edition,1.7,false,RESTART,"[BiblioCraft, Forestry]"
ThermalFoundation,Thermal Foundation,1.7.10R1.2.0,false,DEPENDENCIES,"[CoFHCore@[1.7.10R3.0.3,)]"
ThermalExpansion,Thermal Expansion,1.7.10R4.0.3B1,false,RESTART,"[CoFHCore@[1.7.10R3.0.3,), ThermalFoundation@[1.7.10R1.2.0,)]"
BigReactors,Big Reactors,0.4.3A,false,RESTART,"[Forge@[10.13.2.1291,), CoFHCore, ThermalExpansion]"
BinnieCore,Binnie Core,2.0-pre14,false,RESTART,[Forestry]
Botany,Botany,2.0-pre14,false,RESTART,[BinnieCore]
ExtraBees,Extra Bees,2.0-pre14,false,RESTART,[BinnieCore]
ExtraTrees,Extra Trees,2.0-pre14,false,RESTART,[BinnieCore]
Genetics,Genetics,2.0-pre14,false,RESTART,[BinnieCore]
Thaumcraft,Thaumcraft,4.2.3.5,false,DEPENDENCIES,"[Forge@[10.13.2,), Baubles@[1.0.1.10,)]"
Botania,Botania,r1.7-224,false,RESTART,"[Baubles, Thaumcraft]"
BrandonsCore,Brandon's Core,1.0.0.7,false,RESTART,[]
BuildCraft|Builders,BC Builders,7.1.9,false,RESTART,[BuildCraft|Core@7.1.9]
BuildCraft|Transport,BC Transport,7.1.9,false,RESTART,[BuildCraft|Core@7.1.9]
BuildCraft|Energy,BC Energy,7.1.9,false,RESTART,[BuildCraft|Core@7.1.9]
BuildCraft|Silicon,BC Silicon,7.1.9,false,RESTART,[BuildCraft|Core@7.1.9]
BuildCraft|Robotics,BC Robotics,7.1.9,false,RESTART,[BuildCraft|Core@7.1.9]
BuildCraft|Factory,BC Factory,7.1.9,false,RESTART,[BuildCraft|Core@7.1.9]
CarpentersBlocks,Carpenter's Blocks,3.3.7,false,RESTART,"[Forge@[10.13.0.1180,)]"
ChickenChunks,ChickenChunks,1.3.4.19,false,RESTART,"[CodeChickenCore@[1.0.3,)]"
TwilightForest,The Twilight Forest,2.3.7,false,RESTART,[]
ForgeMultipart,Forge Multipart,1.2.0.345,false,DEPENDENCIES,[]
chisel,Chisel,2.9.2.8,false,RESTART,"[EE3, ForgeMultipart, Thaumcraft, appliedenergistics2, Railcraft, AWWayofTime, TwilightForest]"
ComputerCraft,ComputerCraft,1.74,false,RESTART,[]
EnderStorage,EnderStorage,1.4.7.33,false,RESTART,"[CodeChickenCore@[1.0.5,)]"
MineFactoryReloaded,MineFactory Reloaded,1.7.10R2.8.0,false,DEPENDENCIES,"[FML@[7.10.0.1217,7.11), Forge@[10.13.1.1217,10.14), CoFHCore@[1.7.10R3.0.1,)]"
OpenComputers,OpenComputers,1.5.18.36,false,RESTART,"[BuildCraft|Core, ComputerCraft, EnderStorage, ForgeMultipart, IC2, MineFactoryReloaded, ProjRed|Transmission, RedLogic, StargateTech2, Thaumcraft, ThermalExpansion]"
Waila,Waila,1.5.10,false,DEPENDENCIES,"[NotEnoughItems@[1.0.4.0,)]"
CompactMachines,Compact Machines,1.7.10-1.20,false,RESTART,"[appliedenergistics2, ProjRed|Transmission, OpenComputers, Waila, Botania, LookingGlass]"
compactstorage,CompactStorage,v2.0.0a,false,RESTART,[]
CustomChestLoot,Custom Chest Loot,1.1.1,false,RESTART,[]
PTRModelLib,PTRModelLib,1.0.0,false,RESTART,[]
props,Decocraft,2.1.1,false,RESTART,"[PTRModelLib@[1.0.0,)]"
DescriptionTags,Description Tags,1.0,false,RESTART,[]
Ding,Ding,MC1.7.10,false,RESTART,[]
DraconicEvolution,Draconic Evolution,1.0.1c,false,RESTART,"[NotEnoughItems, NotEnoughItems, ThermalExpansion, ThermalFoundation]"
DragonMounts,Dragon Mounts,r41-1.7.10,false,RESTART,[]
eplus,Enchanting Plus,3.0.2-d,false,RESTART,[]
enchantview,EnchantView,4.1.0,false,RESTART,[thebombzenapi]
Enchiridion,Enchiridion,1.1,false,RESTART,"[Forge@[10.12.1.1082,)]"
endercore,EnderCore,1.7.10-0.1.0.25_beta,false,DEPENDENCIES,[ttCore]
GalacticraftCore,Galacticraft Core,3.0.11,false,DEPENDENCIES,"[Forge@[10.12.2.1147,), FML@[7.2.217.1147,), Micdoodlecore, IC2, BuildCraft|Core, BuildCraft|Energy, IC2]"
Mekanism,Mekanism,8.1.7,false,DEPENDENCIES,"[ForgeMultipart, BuildCraft, BuildCraftAPI, IC2, CoFHCore, ComputerCraft, Galacticraft API, MetallurgyCore]"
EnderIO,Ender IO,1.7.10-2.2.8.381,false,RESTART,"[Forge@10.13.0.1150,), MineFactoryReloaded, appliedenergistics2@[rv2-beta-8,)]"
enhancedportals,EnhancedPortals,3.0.12,false,RESTART,[ThermalExpansion]
extrabuttons,ExtraButtons,1.7.10.1,false,RESTART,[]
extracells,Extra Cells 2,2.2.73,false,RESTART,"[LogisticsPipes|Main, Waila, appliedenergistics2]"
ExtraUtilities,Extra Utilities,1.2.11,false,RESTART,"[Forge@[10.13.2.1291,), ForgeMultipart@[1.2.0.336,), Baubles, ThermalFoundation, EE3]"
harvestcraft,Pam's HarvestCraft,1.7.10j,false,RESTART,[]
ImmersiveEngineering,Immersive Engineering,0.5.4,false,RESTART,[Railcraft]
Mantle,Mantle,1.7.10-0.3.2.jenkins184,false,DEPENDENCIES,"[Forge@[10.13,)]"
TConstruct,Tinkers' Construct,1.7.10-1.8.7.build979,false,DEPENDENCIES,"[Forge@[10.13.3.1384,11.14), Mantle@[1.7.10-0.3.2,), MineFactoryReloaded@[1.7.10R2.8.0RC7,), ThermalExpansion@[1.7.10R4.0.0RC2,), ThermalFoundation@[1.7.10R1.0.0RC3,), armourersWorkshop@[1.7.10-0.28.0,), CoFHAPI|energy, CoFHCore, battlegear2, ZeldaItemAPI, DynamicSkillsAPI, NotEnoughItems, Waila]"
ExtraTiC,ExtraTiC,1.4.5,false,RESTART,"[TConstruct, Metallurgy@[4.0.4,], Natura, Mekanisum, appliedenergistics2, BiomesOPlenty, TSteelworks, BigReactors, ExtraUtilities, harvestcraft, progressiveautomation, ThermalFoundation, nevermine]"
farseek,Farseek,1.0.10,false,RESTART,"[Forge@[10.13.1.1217,), terrafirmacraft@[0.79.23,)]"
FastCraft,FastCraft,1.21,false,RESTART,[]
FlatSigns,Flat Signs,2.1.0.19,false,RESTART,[]
fossil,Fossils and Archeology Revival,1.7.10 Build 7.2.1,false,RESTART,[]
GalacticraftMars,Galacticraft Planets,3.0.11,false,RESTART,[GalacticraftCore]
ThaumicTinkerer,Thaumic Tinkerer,unspecified,false,RESTART,"[Forge@[10.12.1.1112,), Thaumcraft@[4.2.2.0,], IC2, ThaumicTinkererKami, Waila, ForgeMultipart, ComputerCraft]"
MagicBees,Magic Bees,1.7.10-2.3.6,false,RESTART,"[Forestry@[3.6,), Thaumcraft, ExtraBees, EE3, ArsMagica, TConstruct, Railcraft, ThermalFoundation, ThermalExpansion, RedstoneArsenal, AWWayofTime, Botania, appliedenergistics2]"
gendustry,GenDustry,1.6.0.125,false,RESTART,"[Forestry@[3.6.0.0,), BuildCraft|energy, BuildCraft|Silicon, IC2, CoFHCore, BinnieCore, ExtraBees, ExtraTrees, MineFactoryReloaded, MagicBees, bdlib@[1.9.2.104,)]"
advgenerators,Advanced Generators,0.9.18.113,false,RESTART,"[pressure, BuildCraft|energy, BuildCraft|Silicon, IC2, CoFHCore, ThermalExpansion, eng_toolbox, minechem, bdlib]"
Growthcraft,Growthcraft,1.7.10-2.3.0,false,DEPENDENCIES,[]
Growthcraft|Bamboo,Growthcraft Bamboo,1.7.10-2.3.0,false,RESTART,[Growthcraft]
Growthcraft|Cellar,Growthcraft Cellar,1.7.10-2.3.0,false,DEPENDENCIES,[Growthcraft]
Growthcraft|Apples,Growthcraft Apples,1.7.10-2.3.0,false,RESTART,"[Growthcraft, Growthcraft|Cellar]"
Growthcraft|Bees,Growthcraft Bees,1.7.10-2.3.0,false,RESTART,"[Growthcraft, Growthcraft|Cellar]"
Growthcraft|Grapes,Growthcraft Grapes,1.7.10-2.3.0,false,RESTART,"[Growthcraft, Growthcraft|Cellar]"
Growthcraft|Hops,Growthcraft Hops,1.7.10-2.3.0,false,RESTART,"[Growthcraft, Growthcraft|Cellar]"
Growthcraft|Rice,Growthcraft Rice,1.7.10-2.3.0,false,RESTART,"[Growthcraft, Growthcraft|Cellar]"
Growthcraft|Fishtrap,Growthcraft Fishtrap,1.7.10-2.3.0,false,RESTART,[Growthcraft]
iChunUtil,iChunUtil,4.2.2,false,DEPENDENCIES,"[Forge@[10.13.2.1291,)]"
Hats,Hats,4.0.1,false,RESTART,"[iChunUtil@[4.0.0,)]"
inventorytweaks,Inventory Tweaks,1.59-dev-152-cf6e263,false,RESTART,"[FML@[7.2.0,), Forge@[10.12.1,)]"
journeymap,JourneyMap,@JMVERSION@,false,YES,"[Forge@[10.13.2.1291,)]"
LunatriusCore,LunatriusCore,1.1.2.21,false,DEPENDENCIES,"[Forge@[10.13.0.1180,)]"
Mariculture,Mariculture,1.7.10-1.2.4.2a,false,RESTART,"[Forge@[10.13.0.1197,), Forestry, AWWayofTime@[v1.0.1,), BiomesOPlenty@[2.0.0,), HardcoreEnderExpansion, TConstruct, ThermalFoundation]"
MariTech,Marine Technlogy,1.0,false,RESTART,[Mariculture]
RadixCore,RadixCore,2.0.3,false,DEPENDENCIES,[]
MCA,Minecraft Comes Alive,1.7.10-5.0.7.2,false,RESTART,"[RadixCore@[2.0.2,)]"
MekanismGenerators,MekanismGenerators,8.1.7,false,RESTART,[Mekanism]
MineFactoryReloaded|CompatAppliedEnergistics,MFR Compat: Applied Energistics,1.7.10R2.8.0,false,RESTART,"[MineFactoryReloaded, appliedenergistics2]"
MineFactoryReloaded|CompatAtum,MFR Compat: Atum,1.7.10R2.8.0,false,RESTART,"[MineFactoryReloaded, Atum]"
MineFactoryReloaded|CompatBackTools,MFR Compat: BackTools,1.7.10R2.8.0,false,RESTART,"[MineFactoryReloaded, mod_BackTools]"
MineFactoryReloaded|CompatBuildCraft,MFR Compat: BuildCraft,1.7.10R2.8.0,false,RESTART,"[MineFactoryReloaded, BuildCraft|Core]"
MineFactoryReloaded|CompatChococraft,MFR Compat: Chococraft,1.7.10R2.8.0,false,RESTART,"[MineFactoryReloaded, chococraft]"
MineFactoryReloaded|CompatExtraBiomes,MFR Compat: ExtraBiomes,1.7.10R2.8.0,false,RESTART,"[MineFactoryReloaded, ExtrabiomesXL]"
MineFactoryReloaded|CompatForestry,MFR Compat: Forestry,1.7.10R2.8.0,false,RESTART,"[MineFactoryReloaded, Forestry]"
MineFactoryReloaded|CompatForgeMicroblock,MFR Compat: ForgeMicroblock,1.7.10R2.8.0,false,RESTART,[MineFactoryReloaded]
MineFactoryReloaded|CompatIC2,MFR Compat: IC2,1.7.10R2.8.0,false,RESTART,"[MineFactoryReloaded, IC2]"
MineFactoryReloaded|CompatMystcraft,MFR Compat: Mystcraft,1.7.10R2.8.0,false,RESTART,"[MineFactoryReloaded, Mystcraft]"
MineFactoryReloaded|CompatProjRed,MFR Compat ProjectRed,1.7.10R2.8.0,false,RESTART,"[MineFactoryReloaded, ProjRed|Core, ProjRed|Exploration]"
MineFactoryReloaded|CompatRailcraft,MFR Compat: Railcraft,1.7.10R2.8.0,false,RESTART,"[MineFactoryReloaded, Railcraft]"
MineFactoryReloaded|CompatSufficientBiomes,MFR Compat: Sufficient Biomes,1.7.10R2.8.0,false,RESTART,"[MineFactoryReloaded, EmasherWorldGen]"
MineFactoryReloaded|CompatThaumcraft,MFR Compat: Thaumcraft,1.7.10R2.8.0,false,RESTART,"[MineFactoryReloaded, Thaumcraft]"
MineFactoryReloaded|CompatThermalExpansion,MFR Compat: Thermal Expansion,1.7.10R2.8.0,false,RESTART,"[MineFactoryReloaded, ThermalExpansion]"
MineFactoryReloaded|CompatTConstruct,MFR Compat: Tinkers' Construct,1.7.10R2.8.0,false,RESTART,"[MineFactoryReloaded, TConstruct]"
MineFactoryReloaded|CompatTwilightForest,MFR Compat: TwilightForest,1.7.10R2.8.0,false,RESTART,"[MineFactoryReloaded, TwilightForest]"
MineFactoryReloaded|CompatVanilla,MFR Compat: Vanilla,1.7.10R2.8.0,false,RESTART,[MineFactoryReloaded]
MineTweaker3,MineTweaker 3,3.0.9B,false,DEPENDENCIES,[]
MTRM,MineTweakerRecipeMaker,1.0,false,RESTART,[]
modtweaker2,Mod Tweaker 2,0.9.4,false,RESTART,[MineTweaker3]
Morph,Morph,0.9.2,false,RESTART,"[iChunUtil@[4.0.0,)]"
Morpheus,Morpheus,1.7.10-1.6.10,false,RESTART,[]
MutantCreatures,Mutant Creatures,1.4.9,false,RESTART,[]
NEIAddons,NEI Addons,1.12.11.36,false,RESTART,[NotEnoughItems]
NEIAddons|Developer,NEI Addons: Developer Tools,1.12.11.36,false,RESTART,[NEIAddons]
NEIAddons|AppEng,NEI Addons: Applied Energistics 2,1.12.11.36,false,RESTART,"[NEIAddons, appliedenergistics2]"
NEIAddons|Botany,NEI Addons: Botany,1.12.11.36,false,RESTART,"[NEIAddons, Botany]"
NEIAddons|Forestry,NEI Addons: Forestry,1.12.11.36,false,RESTART,"[NEIAddons, Forestry]"
NEIAddons|CraftingTables,NEI Addons: Crafting Tables,1.12.11.36,false,RESTART,[NEIAddons]
NEIAddons|ExNihilo,NEI Addons: Ex Nihilo,1.12.11.36,false,RESTART,[exnihilo]
neiintegration,NEI Integration,1.0.12,false,RESTART,"[Forestry@[3.6.0,)]"
NetherOres,Nether Ores,1.7.10R2.3.0,false,RESTART,"[FML@[7.10.0.1217,7.11), Forge@[10.13.1.1217,10.14), CoFHCore@[1.7.10R3.0.1,)]"
NodalMechanics,NodalMechanics,1.7.10R1.0,false,RESTART,[Thaumcraft]
neresources,Not Enough Resources,0.1.0.106,false,RESTART,"[NotEnoughItems, CoFHCore]"
Oceancraft,Oceancraft,1.4.1,false,RESTART,[]
OpenMods,OpenMods,0.8,false,DEPENDENCIES,[OpenModsCore]
OpenBlocks,OpenBlocks,1.4.4,false,RESTART,"[OpenMods@[0.8,0.9)]"
OpenPeripheralCore,OpenPeripheralCore,1.2,false,RESTART,"[OpenMods@[0.8,0.9), ComputerCraft@[1.70,], OpenComputers@[1.5.0,]]"
OpenPeripheral,OpenPeripheralAddons,0.4,false,RESTART,"[OpenMods@[0.8,0.9), OpenPeripheralApi@[3.3.1,3.4), ComputerCraft@[1.70,]]"
OpenPeripheralIntegration,OpenPeripheralIntegration,0.3,false,RESTART,"[OpenMods@[0.8,0.9), OpenPeripheralApi@[3.3.1,3.4), ComputerCraft@[1.70,], appliedEnergistics-2, IC2, EnderStorage, BuildCraft|Core, Forestry, Mystcraft, Railcraft, Thaumcraft, ThermalExpansion]"
origin,Origin,6.0.0,false,DEPENDENCIES,[]
clayspawn,Pam's Clay Spawn,1.7.10a,false,RESTART,[]
Progression,Progression,0.4.1,false,RESTART,[]
RandomThings,Random Things,2.2.4,false,RESTART,[]
reccomplex,Recurrent Complex,0.9.6.3,false,RESTART,[ivtoolkit]
rftools,RFTools,3.50,false,RESTART,"[Forge@[10.13.2.1291,), CoFHLib@[1.0.3,), McJtyLib@[1.6.1,)]"
Roguelike,Roguelike Dungeons,1.3.6.3,false,RESTART,[]
SimpleLabels,SimpleLabels,@VERSION@,false,RESTART,[]
simplyjetpacks,Simply Jetpacks,1.5.1,false,RESTART,"[Forge@[10.13.2.1291,), ThermalExpansion, RedstoneArsenal, RArm, EnderIO@[1.7.10-2.1.3.243,), BuildCraft|Core@[6.4.15,7.0.0),[7.0.4,)]"
SolarFlux,Solar Flux,1.7.10-0.8b,false,RESTART,"[ThermalExpansion, ThermalFoundation]"
SSR,Soul Shards Reborn,rc3,false,RESTART,[]
Stackie,Stackie,1.6.0.36,false,RESTART,"[Forge@[10.13.0.1180,), LunatriusCore@[1.1.2.21,)]"
statues,Statues,2.1.4,false,RESTART,[asielib]
stefinusguns,New Stefinus Guns,0.5.2,false,RESTART,[]
tcnodetracker,TC Node Tracker,1.1.2,false,RESTART,"[Forge@[10.12.1.1112,), Thaumcraft]"
thaumcraftneiplugin,Thaumcraft NEI Plugin,@VERSION@,false,RESTART,[Thaumcraft]
thaumicenergistics,Thaumic Energistics,0.8.10.10,false,RESTART,"[appliedenergistics2@[rv2-stable-1,), Thaumcraft@[4.2.3.5,), Waila, extracells]"
thaumicexpansion,Thaumic Expansion,3.0.0,false,RESTART,"[Thaumcraft@[4.2,), origin@[5,), CoFHCore@[1.7.10R3.0.0RC7,), ThermalFoundation@[1.7.10R1.0.0RC7,), ThermalExpansion@[1.7.10R4.0.0RC7,)]"
erebus,Erebus,0.3a,false,RESTART,"[Forge@[10.13.4.1448,)]"
ThermalDynamics,Thermal Dynamics,1.7.10R1.1.0,false,RESTART,"[ThermalFoundation@[1.7.10R1.2.0,)]"
TiCTooltips,TiC Tooltips,1.2.5,false,RESTART,"[TConstruct@[1.7.10-1.8,), ExtraTiC, TSteelworks, Mariculture]"
TMechworks,Tinkers' Mechworks,0.2.14.100,false,RESTART,"[Forge@[10.13.0.1208,], TConstruct, Mantle]"
TooMuchRain,TooMuchRain,%VERSION%,false,RESTART,"[Forge@[10.12.1.1112,)]"
wailaevents,Waila Events,1.0.0,false,RESTART,[Waila]
WailaHarvestability,Waila Harvestability,1.1.2,false,RESTART,"[TConstruct, ExtraTiC, TSteelworks, Mariculture]"
wailaplugins,WAILA Plugins,MC1.7.10-0.1.2-21,false,RESTART,"[Forge@[10.13.0.1208,), endercore@[1.7.10-0.0.1.10_alpha,), Waila]"
warpbook,Warp Book,2.0.null,false,RESTART,[]
wawla,What Are We Looking At,1.3.1,false,RESTART,[Waila]
witchery,Witchery,0.24.1,false,RESTART,"[Forge@[10.13.2.1277,), MineFactoryReloaded, NotEnoughItems, Waila, ForgeMultipart, AWWayofTime]"
worldedit,WorldEdit,6.0-beta-01,false,RESTART,[]
WR-CBE|Core,WR-CBE Core,1.4.1.9,false,DEPENDENCIES,"[CodeChickenCore@[1.0.4,), ForgeMultipart]"
WR-CBE|Addons,WR-CBE Addons,1.4.1.9,false,RESTART,[WR-CBE|Core]
WR-CBE|Logic,WR-CBE Logic,1.4.1.9,false,RESTART,"[WR-CBE|Core, ForgeMultipart]"
WTFCore,WhiskyTangoFox's Core,1.63,false,DEPENDENCIES,[UndergroundBiomes]
CaveBiomes,WhiskyTangoFox's CaveBiomes,1.50,false,RESTART,"[UndergroundBiomes, WTFCore@[1.63,)]"
McMultipart,Minecraft Multipart Plugin,1.2.0.345,false,RESTART,[]
MrTJPCoreMod,MrTJPCore,1.1.0.31,false,RESTART,[]
denseores,Dense Ores,1.0,false,RESTART,[*]
HungerOverhaul,Hunger Overhaul,1.7.10-1.0.0.jenkins75,false,RESTART,"[Forge@[10.13,), AppleCore, TConstruct, harvestcraft, temperateplants, randomplants, weeeflowers, Natura, IC2, *]"
ForgeMicroblock,Forge Microblocks,1.2.0.345,false,RESTART,"[ForgeMultipart, *]"
asielibcore,AsieLib CoreMod,,true,NEVER,[]

**Comment by way2muchnoise** [comment]
@fishmealx pls use pastebin or alike to post mod lists or logs.
