### ISSUE TITLE
Crash with forestry 4.2.x

### ISSUE THREAD

**Issue by Xen1290** [hilburn/NotEnoughResources#63]
https://gist.github.com/Xen1290/c9d520feb9d60dd88e8c
@hilburn @way2muchnoise

**Comment by border999** [comment]
it would be a very good idea to fix this

**Comment by way2muchnoise** [comment]
@Xen1290 @border999 A build with the fix has been send to Curse Forge once it gets accepted (give or take 10 mins from writing this) then you'll be able to download it.

**Comment by Xen1290** [comment]
Thanks!
