### ISSUE TITLE
[1.0.121] Server crash on startup (compability with Forestry)

### ISSUE THREAD

**Issue by Xiaminou** [hilburn/NotEnoughResources#66]
Server crashes on startup and does not generate a crash report.
Here is the full log, the "crash report" is at the end and seems to indicate a problem between NER and Forestry, is it compatible with forestry 3.6?
Full Log: https://drive.google.com/file/d/0B090g8mHJkCWVTFKMS0ySGlZb28/view?usp=sharing

**Comment by way2muchnoise** [comment]
it should be compatible

**Comment by Xiaminou** [comment]
Did you fix it or did you just close?

**Comment by way2muchnoise** [comment]
It should be fixed try either the latest alpha or beta on CurseForge

**Comment by Xiaminou** [comment]
cool
