### ISSUE TITLE
Server Keeps Shutting Down?

### ISSUE THREAD

**Issue by DerpyShadowz** [hilburn/NotEnoughResources#70]
This could be a Forestry issue or a NotEnoughResources issue, I'm not sure.
But it looks like either of them, because this piece of code keeps popping up each time the server shuts down.

[EDITED] Don't post logs in issues, provide a link to a pastebin, gist or alike

**Comment by way2muchnoise** [comment]
What version of NER are you using? Also could you remove the log from the issue and make a link to pastebin or alike

**Comment by DerpyShadowz** [comment]
@way2muchnoise 
Version 0.1.0-121, the most recent one I could find on Curse

**Comment by way2muchnoise** [comment]
Try 0.1.0-122 http://minecraft.curseforge.com/projects/notenoughresources/files/2272500

**Comment by DerpyShadowz** [comment]
@way2muchnoise 
Alright, will try that. Thanks for now.

**Comment by DerpyShadowz** [comment]
@way2muchnoise 
It seems to work, so thanks for that.
