### ISSUE TITLE
Around 10k chunks "All" profile scan will not write a new file

### ISSUE THREAD

**Issue by undeadbanana** [hilburn/NotEnoughResources#76]
I know, excessive maybe, but it did complete the scan (Allowed me to perform a new scan) but after completing scans around that number and up will not write a new file.

**Comment by way2muchnoise** [comment]
Pretty sure this is a report for [way2muchnoise/JustEnoughResources](https://github.com/way2muchnoise/JustEnoughResources) as NER doesn't have profiling iirc

**Comment by undeadbanana** [comment]
Yeah, my bad. Lol. I was looking at JER's git and was like wtf, where'd my report go. I guess I clicked his link to NEI instead of going to his Github.
